### PR TITLE
add ze files

### PR DESCRIPTION
**Pull request by rpappalax**

### CODE REVIEW

**Comment by bravenewrichard** [comment]
test

**Comment by bravenewrichard** [comment]
test

**Comment by rpappalax** [comment]
device:
        - model: Nexus9
          version: 25
          locale: en
          orientation: portrait
        - model: Pixel2
          version: 28
          locale: en
          orientation: portrait

MatrixResultsReport
  19 / 21 (90.48%)
  2 matrices failed

  matrix-384znhb0etuz8 
  https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7464069115387022443

  matrix-1m58o8tnihg49 
  https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7406268022315984038

**Comment by bravenewrichard** [comment]
device:
- model: Nexus9
version: 25
locale: en
orientation: portrait
- model: Pixel2
version: 28
locale: en
orientation: portrait

MatrixResultsReport
19 / 21 (90.48%)
2 matrices failed

matrix-384znhb0etuz8
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7464069115387022443

matrix-1m58o8tnihg49
https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7406268022315984038

**Comment by bravenewrichard** [comment]
**DEVICES**
X86
:
         - model: Nexus9
           version: 25
           locale: en
           orientation: portrait
         - model: Pixel2
           version: 28
           locale: en
           orientation: portrait
       flaky-test-attempts: 0
 
     
**TEST REPORT**

   19 / 21 (90.48%)
   2 matrices failed
 
   matrix-384znhb0etuz8 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7464069115387022443
 
   matrix-1m58o8tnihg49 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7406268022315984038
 
 
 
 ERROR: UI test run failed, please check above URL

**Comment by bravenewrichard** [comment]
**DEVICES**
X86

 - model Nexus9
           version 25
           locale en
           orientation portrait
 - model Pixel2
           version 28
           locale en
           orientation portrait
       flaky-test-attempts 0

     
**TEST REPORT**

   19 / 21 (90.48%)
   2 matrices failed
 
   matrix-384znhb0etuz8 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7464069115387022443
 
   matrix-1m58o8tnihg49 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7406268022315984038
 
 
 
 ERROR: UI test run failed, please check above URL

**Comment by bravenewrichard** [comment]
**DEVICES**
X86

         - model Nexus9
           version 25
           locale en
           orientation portrait
         - model Pixel2
           version 28
           locale en
           orientation portrait
       flaky-test-attempts 0
 
     
**TEST REPORT**

   19 / 21 (90.48%)
   2 matrices failed
 
   matrix-384znhb0etuz8 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7464069115387022443
 
   matrix-1m58o8tnihg49 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7406268022315984038
 
 
 
 ERROR: UI test run failed, please check above URL

**Comment by bravenewrichard** [comment]
**DEVICES**
X86

         - model Nexus6
           version 25
           locale en
           orientation portrait
         - model Pixel2
           version 28
           locale en
           orientation portrait
       flaky-test-attempts 0
 
     
**TEST REPORT**
UI tests passed

**Comment by bravenewrichard** [comment]
**TEST REPORT**

   27 / 27 (100.00%)
 
**DEVICES**
X86
UI tests passed!

**Comment by bravenewrichard** [comment]
**TEST REPORT**
All UI tests passed!
**DEVICES**
X86

         - model Nexus6
           version 25
           locale en
           orientation portrait
         - model Pixel2
           version 28
           locale en
           orientation portrait
       flaky-test-attempts 0

**Comment by bravenewrichard** [comment]
**TEST REPORT**

   19 / 21 (90.48%)
   2 matrices failed
 
   matrix-384znhb0etuz8 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7464069115387022443
 
   matrix-1m58o8tnihg49 
   https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/7406268022315984038
 
 
 
 ERROR: UI test run failed, please check above URL
 
**DEVICES**
X86

         - model Nexus9
           version 25
           locale en
           orientation portrait
         - model Pixel2
           version 28
           locale en
           orientation portrait
       flaky-test-attempts 0

**Comment by bravenewrichard** [comment]
**TEST REPORT**
All UI tests passed!

**DEVICES**
X86

         - model Nexus6
           version 25
           locale en
           orientation portrait
         - model Pixel2
           version 28
           locale en
           orientation portrait
       flaky-test-attempts 0

**Pull request merged**
